name: Deploy RacerAPI Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- IMPORTANT

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install MkDocs + Plugins
        run: |
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-awesome-pages-plugin

      - name: Build & Deploy Docs
        working-directory: src/docs
        run: mkdocs gh-deploy --force
